spring:
  application:
    name: test-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        #Query A 参数有A就行，Query B,C 参数B的值为C即可
        #实现针对于“http://localhost:88/zsy0216?url=baidu”，转发到“https://www.github.com/zsy0216”，
        #- id: github_route
        #  uri: https://www.github.com
        #  predicates:
        #    - Query=url,github
        # admin   是从前端请求的 http://localhost:88  转到  http://localhost:88   其余参数不变
        - id: admin_route
          uri: http://localhost:10001
          predicates:
            - Path=/test2/**
server:
  port: 10000
